#!/bin/bash -ea

target=${1-build}

echo "building shared modules with target=$target"

echo "node: $(node --version)"
echo "yarn: $(yarn --version)"

cd "$(git rev-parse --show-toplevel)"

ls -l node_modules shared/node_modules shared/*/node_modules | grep /yarn/link/ || true

apps2="common options"

yarn install --non-interactive

build() {
  echo
  echo "### shared/$@ ###"
  set -ev

  cd shared/$1
  yarn run $target
}

if type -p parallel; then
    set -x
    parallel --gnu build ::: $apps2
else
    echo "For faster build, install GNU parallel."
    for app in $apps2; do (build $app); done
fi
